service: hello

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-east-1

package:
  artifact: build/libs/hello-dev-all.jar

functions:
  hello:
    handler: uk.co.logiccache.Handler
    events:
      - http:
          path: hello
          method: get